version: '3.8'

services:
  s3Server:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /data/minio/config/config.env:/etc/config.env
      - /data/minio/data:/mnt/data
    environment:
      MINIO_ROOT_USER: AdminUserAdmin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}  # Pass MINIO_ROOT_PASSWORD here
      MINIO_ENV_FILE: /etc/config.env
    command: ["minio", "server", "--console-address", ":9001"]
    stdin_open: true
    tty: true
    container_name: s3Server
